### ISSUE TITLE
As a user I can see all the upcoming court hearings

### ISSUE THREAD

**Issue by eadehemingway** [fac-13/CourtWatch#1]
- [x] add courts info to database #34 
- [x] add get all hearings query #31 
- [x] add schedule / get all hearings routes #32 
- [x] add hearings list view react components - Schedule page #33
