### ISSUE TITLE
As a user I can click on a hearing and go to a page with more details about it 

### ISSUE THREAD

**Issue by eadehemingway** [fac-13/CourtWatch#4]
- [x] Create query to DB #27 
- [x] Create route and handler on server #28 
- [x] Fetch data of hearing from database #27 
- [x] Populate hearing view with data #28 
- [x] Create hearing details UI with react components #29
